### ISSUE TITLE
Unable to navigate via TV box

### ISSUE THREAD

**Issue by vigermam** [DSteve595/Put.io#30]
I used to use this app in my XiaoMi Box, I can NAV though the menu by click the up down left right and enter button on the Andriod remote. But don't know since when the app stops supporting the TV remote. As this might affect a lot of users like myself, who relies watch put site mostly in TV.

**Comment by DSteve595** [comment]
Hm, I fixed this a while ago, there might've been a regression. I'll check it out!

**Comment by vigermam** [comment]
Hi Steve, 

I've re-installed the lastest version. Seems the problem is gone. Thanks for your time. However, I'm having different problem with video play now. I will open another ticket for that.

Ryan Zhang
