### ISSUE TITLE
Video Play Crash the App

### ISSUE THREAD

**Issue by vigermam** [DSteve595/Put.io#32]
I'm using this app on Android TV box, I have a remote control with navigation button and option button. In previous version, I be able to long press and choose the video file to select which video player to use with. (Or system pops out an option menu). However, in the lastest version, besides nav around, once click on video play, the app just crashed. And the long press and option button doesn't do anything any where in app. Also, it seems the nav button on remote won't allow user to active all function that previous version have. Such as watch the download progress, and setting, etc..
Is that something we can fix? 
Thanks so much developers!

**Comment by DSteve595** [comment]
I'm not super familiar with the TV functionality (@sregg implemented it) but I'll see if I can find what's wrong when I can.

**Comment by vigermam** [comment]
Hi Steve,

The last App works with my TV box is  2.1 beta 2 released on Oct 15, 2014. 

After that, the interface no longer function as you can use the remote to control it.

**Comment by DSteve595** [comment]
Is this still happening with the latest beta?
