### ISSUE TITLE
Controls not working on Sony Bravia KD-65X9305C

### ISSUE THREAD

**Issue by imanel** [DSteve595/Put.io#33]
Yesterday I tested this app on new Sony Bravia TV and it looks like there are some control problems. At first everything looks ok - I'm able to select folder and file within. Then black screen shows with control overlay, on which I'm able to select forward/rewind and start/pause. However after movie start playing I'm unable to recall this window in order to pause/rewind video. I've tested on both "touch" pilot and "normal" one and no buttons are helping. I'm able to use everything else (back button, home button etc.) so it isn't pilot problems. I'm also able to recall this overlay by opening quick menu (swipe up or down on touchpad) but no buttons are selected and pilot doesn't respond for any movement or clicks on this menu.

Any idea what might be wrong? It's hard to restart movie every time I want to pause ;) If there is any way of debugging I will gladly help.

**Comment by DSteve595** [comment]
I'm not super familiar with the TV functionality (@sregg implemented it) but I'll see if I can find what's wrong when I can.

**Comment by imanel** [comment]
@DSteve595 @sregg any updates on it? If you're busy then could you give me some hint about where should I start searching? I'm not familiar with Android TV, but had some experience with "plain" Android programming.

**Comment by DSteve595** [comment]
I don't have a lot of time to work on it now unfortunately.
If you want to try and help, I'd start with the classes in the '.tv'
package. They contain pretty much all of the TV UI.

**Comment by wouterdebie** [comment]
Same is happening on Amazon Fire TV. I might be able to try and help after I familiarize myself with the code.

**Comment by DSteve595** [comment]
@wouterdebie Is it still happening after @yuvalt's fix? They're in the Play Store beta, and latest master.

**Comment by wouterdebie** [comment]
@DSteve595 I'll check tomorrow and let you know. Any idea how I install the Play Store beta on my Fire TV? (Got it today and still familiarizing myself with the ecosystem)

**Comment by DSteve595** [comment]
I put .apks in the Releases section here on GitHub.

**Comment by wouterdebie** [comment]
Ah yes, I found them. Will test tomorrow and report back.

Thanks!

**Comment by wouterdebie** [comment]
Works! Thanks!

**Comment by DSteve595** [comment]
Sweet, glad to hear it.
