### ISSUE TITLE
Change the redirect url from HTTP to HTTPS

### ISSUE THREAD

**Issue by jonalmeida** [DSteve595/Put.io#38]
You might have to buy an SSL cert but it's safer to do that than just your OAUTH token go out in plain text.

Alternatively, let's hope the [Let's Encrypt project](https://letsencrypt.org/) launches sooner ;).

**Comment by DSteve595** [comment]
Actually, I have an SSL certificate on my (non-existent) site. I'll see if changing it here and on Put.io's end works.

**Comment by jonalmeida** [comment]
\o/
