### ISSUE TITLE
Playback fails to start

### ISSUE THREAD

**Issue by vsekhar** [DSteve595/Put.io#39]
App version: 3.1.4-beta2
Android: 6.0 MRA58K

Repro:
1. Open app
2. Tap cast button, choose Chromecast (app logo appears on TV)
3. Start playback of a file

Expected:
-file plays

Actual:
-loading progress bar is displayed for about 15 seconds
-blank screen shown for 1 second
-loading progress bar displayed for about 3 seconds
-screen returns to showing the app logo

Confirmed that playback of the same file on the same cast device works fine when casting from the put.io website on Chrome linux.

**Comment by DSteve595** [comment]
Looking into it. Able to provide a stack trace?

**Comment by DSteve595** [comment]
Can't reproduce.

**Comment by vsekhar** [comment]
Seems to be working now
