### ISSUE TITLE
Force close when trying to download

### ISSUE THREAD

**Issue by commarla** [DSteve595/Put.io#41]
Hi,

I have a force close when I try to download something from the app.
I didn't try to uninstall/reinstall but here is the logcat, message is pretty obvious : 

> 11-21 07:53:58.405 845-1731/? I/ActivityManager: START u0 {cmp=com.stevenschoen.putionew/.activities.FileDetailsActivity (has extras)} from uid 10148 on display 0
> 11-21 07:53:58.963 845-863/? I/ActivityManager: Displayed com.stevenschoen.putionew/.activities.FileDetailsActivity: +552ms
> 11-21 07:54:00.572 20050-20107/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
>                                                    Process: com.stevenschoen.putionew, PID: 20050
>                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                        at android.os.AsyncTask$3.done(AsyncTask.java:309)
>                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                        at java.lang.Thread.run(Thread.java:818)
>                                                     Caused by: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/put.io/123456789/AAAAABBBBBBCCCCC.zip: Neither user 10148 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
>                                                        at android.os.Parcel.readException(Parcel.java:1599)
>                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
>                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
>                                                        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
>                                                        at android.content.ContentResolver.insert(ContentResolver.java:1231)
>                                                        at android.app.DownloadManager.enqueue(DownloadManager.java:946)
>                                                        at com.stevenschoen.putionew.PutioUtils.download(PutioUtils.java:389)
>                                                        at com.stevenschoen.putionew.PutioUtils.download(PutioUtils.java:373)
>                                                        at com.stevenschoen.putionew.PutioUtils.downloadFileWithoutUrl(PutioUtils.java:353)
>                                                        at com.stevenschoen.putionew.PutioUtils.access$100(PutioUtils.java:80)
>                                                        at com.stevenschoen.putionew.PutioUtils$1DownloadFileTask.doInBackground(PutioUtils.java:310)
>                                                        at com.stevenschoen.putionew.PutioUtils$1DownloadFileTask.doInBackground(PutioUtils.java:297)
>                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                        at java.lang.Thread.run(Thread.java:818) 
> 11-21 07:54:00.606 845-2110/? W/ActivityManager:   Force finishing activity com.stevenschoen.putionew/.activities.FileDetailsActivity
> 11-21 07:54:01.982 845-1344/? I/WindowState: WIN DEATH: Window{2026be3 u0 com.stevenschoen.putionew/com.stevenschoen.putionew.activities.Putio}
> 11-21 07:54:02.029 845-5609/? I/ActivityManager: Process com.stevenschoen.putionew (pid 20050) has died
> 11-21 07:54:02.030 845-5609/? W/ActivityManager: Scheduling restart of crashed service com.stevenschoen.putionew/.PutioTransfersService in 1000ms
> 11-21 07:54:02.030 845-5609/? W/ActivityManager: Force removing ActivityRecord{8541f7c u0 com.stevenschoen.putionew/.activities.Putio t2160}: app died, no saved state

I am using a nexus 5 with android 6.

Thanks,

**Comment by DSteve595** [comment]
Thanks for the report. On it!

**Comment by DSteve595** [comment]
Fixed in latest beta.

**Comment by commarla** [comment]
And it is working!

First download shown pop up to request permission then the download went fine.

Thanks for the fix.
