### ISSUE TITLE
Horizontal scroll bar appears at bottom when casting

### ISSUE THREAD

**Issue by vsekhar** [DSteve595/Put.io#42]
May cause TV burnin. Possibly due to receiver app selecting incorrect width.

(confirmed no scroll bar when casting from YouTube app or put.io website)

**Comment by DSteve595** [comment]
I'm using the default cast receiver and just passing a stream to the video. Could it be the source video you're using? Or understand?

**Comment by vsekhar** [comment]
I suspect it is the receiver because I can cast the same video to the same Chromecast connected to the same TV, and when I use the app I see the scroll bar, but when I cast from the put.io website I do not. I'm not sure if put.io is using the default receiver as well. I've sent Chromecast feedback to see if it's an issue on the Google side.

**Comment by DSteve595** [comment]
Could you take a picture of the scroll bar?

**Comment by dictvm** [comment]
I'm still having this issue, do you still need a picture of the scrollbar?

**Comment by nickedgar** [comment]
same issue here, casting to a chromecast 1 from android app I get a grey scroll bar on bottom of screen, not present when chromecasting from put.io website

**Comment by DSteve595** [comment]
Really weird. I'm looking into it.

**Comment by vsekhar** [comment]
I've found that if the filename I am casting from the app is really long, the scroll bar appears. If I rename the file via the app to something shorter, I can cast it without scroll bars appearing. The filename element in the receiver page might not be fixed width.

**Comment by DSteve595** [comment]
Well now I feel dumb.
Easy fix, I'll have it out soon.

**Comment by DSteve595** [comment]
Pushed.
