### ISSUE TITLE
Downloading multiple files as a zip fails

### ISSUE THREAD

**Issue by GeorgeHahn** [DSteve595/Put.io#43]
When downloading multiple files, if `zip` is chosen, the downloaded file is a JSON document with the following format, rather than the selected files:

``` json
{
"status": "OK",
"zip_id": 0000000
}
```

**Comment by DSteve595** [comment]
More API changes by put.io without anyone being notified, lol. I'll get to
it as soon as I can.

**Comment by GeorgeHahn** [comment]
Looking at the [documentation around zip downloading](https://put.io/v2/docs/zips.html), I think I might be able to tackle this one.

Essentially, [PutioUtils lines 355 and 360](https://github.com/DSteve595/Put.io/blob/master/app/src/main/java/com/stevenschoen/putionew/PutioUtils.java#L355) need to parse the downloaded file for the zip ID and then return a download call on that URL.

The things I'm not sure about are:
- How should I download the zip ID without actually storing it as a file?
- How should I handle parsing the JSON response?

Cheers!

**Comment by DSteve595** [comment]
This should be fixed as of a few versions ago (forgot to close this).

**Comment by DSteve595** [comment]
Sorry, this shouldn't have been closed. @GeorgeHahn Apologies for missing your comment, would you still want to take a crack at it? I can help with any questions you have (including those two, if they're still relevant). If not, I'll work on it after some bug fixes.

**Comment by DSteve595** [comment]
Fixed as of 4.2 beta 2.
