### ISSUE TITLE
Ability to play/pause when phone is locked

### ISSUE THREAD

**Issue by chevillet** [DSteve595/Put.io#46]
Hello,

On earlier versions, we were able to play/pause from the notification when the phone was locked, it was really convenient.
The play/pause button was located here: 

![image](https://cloud.githubusercontent.com/assets/6911138/15091466/4fd853f2-144a-11e6-83c7-b979545665e9.png)

Any way to bring back this feature?

Thanks!

**Comment by vsekhar** [comment]
I am experiencing this as well.

App version: 3.1.6 (via Play Store)
Device: Nexus 5X
Android: 6.0.1 MTC19U

![screenshot_20160508-192343](https://cloud.githubusercontent.com/assets/415244/15105686/88e940d2-1578-11e6-9052-5a4868c1bafd.png)
![screenshot_20160508-192313](https://cloud.githubusercontent.com/assets/415244/15105692/93b9cf40-1578-11e6-81f6-64c7d341cf26.png)

**Comment by DSteve595** [comment]
Sorry about that! Fix coming soon.

**Comment by DSteve595** [comment]
Fixed in 3.1.7.

**Comment by chevillet** [comment]
Thanks a lot Steven!
