### ISSUE TITLE
App crashes? Videos do not play on FireTV stick

### ISSUE THREAD

**Issue by msteinhoff** [DSteve595/Put.io#49]
Hi, I installed the app (v3.1.6) on my FireTV stick (Fire OS 5.2.1.0 (550144920)) via adb.

Installation went smooth and the app starts just fine and shows all files in my account but when I want to play a video, the screen goes black, the play controls show up (and a preview image for some files) but then nothing happens and after a few seconds the app just exits itself.

Any idea why this happens, what the cause could be or how to debug it?

**Comment by xorq** [comment]
same issue here

**Comment by DSteve595** [comment]
Does still happen on 4.0.2?

**Comment by msteinhoff** [comment]
@DSteve595, I am going to check this out on the weekend.
