### ISSUE TITLE
20170526 Android App Crashes When Casting

### ISSUE THREAD

**Issue by hyoomen** [DSteve595/Put.io#51]
When attempting to cast a video, app crashes: video = mp4 AVC/H264, audio = AAC

**Comment by DSteve595** [comment]
Sorry about that! Fixed in 4.1.1.

**Comment by DSteve595** [comment]
Sorry about that! I just put out an update fixing that.

From: hyoomen
Sent: Friday, May 26, 2017 2:35 PM
To: DSteve595/Put.io
Cc: Subscribed
Subject: [DSteve595/Put.io] 20170526 Android App Crashes When Casting (#51)

When attempting to cast a video, app crashes: video = AVC/x264, audio = AAC
