### ISSUE TITLE
App icon set to default Android icon

### ISSUE THREAD

**Issue by ghost** [DSteve595/Put.io#65]
After the last update from Google Play (v4.3.1 released on May 29th), the application's icon is set to the [default Android app icon](https://upload.wikimedia.org/wikipedia/commons/a/a0/APK_format_icon.png) and not [its usual one](https://lh3.ggpht.com/b1hT_8e8zNLH6r-HFM4aDEQZSR3ptFVLKW5bbbV3MBDdn3q13OD-FPfbLy_NqETHsew=s180). 

I have initially noticed that on my phone (OnePlus 2) but it's also affected the installation on my tablet (Nexus 10). The icon appears like that in both the app drawer section and any shortcuts available.

Definitely not a major issue but thought I'd raise you a bug anyway.

**Comment by DSteve595** [comment]
Sorry about that! Fixed in https://github.com/DSteve595/Put.io/releases/tag/4.3.2.
