### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by sregg** [DSteve595/Put.io#71]
Getting this error when building the repo:

> File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
/Users/simonreggiani/dev/Put.io/app/src/nullnull/debug/google-services.json
/Users/simonreggiani/dev/Put.io/app/src/debug/nullnull/google-services.json
/Users/simonreggiani/dev/Put.io/app/src/nullnull/google-services.json
/Users/simonreggiani/dev/Put.io/app/src/debug/google-services.json
/Users/simonreggiani/dev/Put.io/app/src/nullnullDebug/google-services.json
/Users/simonreggiani/dev/Put.io/app/google-services.json

**Comment by DSteve595** [comment]
Need to get it from a Firebase project of your own. Or alternatively, remove all Firebase code (there isn't much).
