### ISSUE TITLE
streaming often doesn't work

### ISSUE THREAD

**Issue by fallerOfFalls** [DSteve595/Put.io#74]
I get an error
>The location https://api.put.io/v2/files/600010919/mp4/stream%3Foath_token=xxxxxxx cannot be played.

No idea if this is an issue with the app, or with VLC, or with android or with put.io's api.

Doesn't happen all the time. Often the first time I play the file it works, and then if I try to play the same file again it fails. Sometimes force quitting both the put.io app and vlc seems to fix it temporarily. Sometimes not.

**Comment by DSteve595** [comment]
Sorry for the long wait.
Are you still getting this? I _may_ have an idea of what's happening (I've into a few cases where put.io thinks an MP4 is available, but it actually 404s).

**Comment by fallerOfFalls** [comment]
I've not encountered this issue for a while now. Might be because I've switched phones. Might be that they fixed a bug. There was a bug with MP4s being unavailable that I think they have now fixed. So maybe that was it. Let's call this fixed and I'll comment again if it happens again.

Thanks for getting back to me.

**Comment by DSteve595** [comment]
Sounds good, feel free to reopen if you see it again!
