### ISSUE TITLE
app doesn't connect 

### ISSUE THREAD

**Issue by ayoub-benali** [DSteve595/Put.io#75]
The application doesn't connect and I get this screen on startup.

Tried cleanup the cache, reinstalling the app but didn't help.

Using pixel 3 with Android 9

![Screenshot_20190510-163335](https://user-images.githubusercontent.com/1632384/57534944-7258c700-7341-11e9-8865-d5d35e8fcaa9.png)

**Comment by Invvard** [comment]
I just tried on my cell and everything is fine, even logged out and logged in back again.

Have you tried from a different Wifi network or cell carrier ? Sometimes security policies can block domains.

**Comment by DSteve595** [comment]
Hmm, in addition to what @Invvard said, have any firewalls or ad blockers maybe?

**Comment by ayoub-benali** [comment]
yes I am using https://f-droid.org/en/packages/org.blokada.alarm/ and for some reason it decided to block the App now...
White listing the App solved the issue.

Thanks for the help and this awesome App

**Comment by DSteve595** [comment]
Awesome, glad to hear it!
